language: generic
sudo: enabled

git:
  submodules: false

before_install:
  - sudo apt -qq update
  - sudo apt install -y $(grep "^[^#;]" ubuntu-dev-deps.list)
  - sudo apt install -y $(grep "^[^#;]" ubuntu-runtime-deps.list)
  - ./autogen.sh --system

install: make

before_script: cd tests

script:
  - make check-local
  - make check
